### ISSUE TITLE
How can change the icon?

### ISSUE THREAD

**Issue by randyesperben** [eramitgupta/laravel-pwa#1]
Hi! thanks for this! 

I wondering about how to change the icon to install pwa?

Thanks!

**Comment by eramitgupta** [comment]
You can change it here in 'config/pwa.php'

**Comment by TutanRamon** [comment]
I am a bit confused about config/pwa.php. 

There seems to be an array called icons (plural). I suppose this is for all the different icons with different width and heights. 

I want to change the image of the "INSTALL PWA" - button. 

In the source code, i see that the value of asset(config('pwa.manifest.icons.src', 'logo.png')); is being used, but isn't that the array for the other icons?
